import test from 'node:test';
import assert from 'node:assert/strict';
import { engine, request, syntheticPoints } from './helpers.mjs';
const near = (a,b) => assert.ok(Math.abs(a-b)<1e-8, `${a} != ${b}`);
const run = req => { const out=engine.analyze(req); assert.equal(out.ok,true,JSON.stringify(out)); return out; };

test('Wasm numeric and Chinese JSON round-trip',()=>{
  assert.equal(engine.add(2,3),5); assert.deepEqual(engine.echo({label:'简投学堂 😀'}),{label:'简投学堂 😀'});
});

test('documented example is generated by the actual engine',()=>{
  const out=run(request([['2020-01-01',10],['2020-01-02',10],['2020-01-03',15]],{frequency:'daily',payment:100,initial:0,inflation:0,fxRate:1,feeRate:0}));
  assert.equal(out.replay.contributions,2);assert.equal(out.replay.principal,200);assert.equal(out.replay.endValue,300);assert.equal(out.replay.realEndValue,300);
});

test('numeric overflow fails explicitly instead of publishing non-finite results',()=>{
  const out=engine.analyze(request([['2020-01-01',1e-300],['2021-01-01',1e300]],{initial:1e12}));
  assert.equal(out.ok,false);assert.equal(out.error.code,'INVALID_INPUT');
});
test('reject empty, invalid dates, order, duplicates, prices and endpoints',()=>{
  for(const points of [[],[['2020-02-30',10]],[['2020-01-02',10],['2020-01-01',10]],[['2020-01-01',10],['2020-01-01',20]],[['2020-01-01',0]],[['2020-01-01',-1]],[['2020-01-01',null]]]) assert.equal(engine.validateHistory(request(points)).ok,false);
  const req=request([['2020-01-01',10]]); req.history.lastDate='2020-01-02'; assert.equal(engine.analyze(req).ok,false);
});
test('reject invalid calculation options and schema',()=>{
  for(const options of [{frequency:'weekly'},{payment:-1},{fxRate:0},{lotSize:0},{inflation:-100},{scheduleDay:1.5},{feeRate:-1}]) assert.equal(engine.analyze(request([['2020-01-01',10]],options)).ok,false);
  assert.equal(engine.analyze({...request([['2020-01-01',10]]),schemaVersion:2}).ok,false);
});
test('monthly month-end anchors clamp and shift to available dates',()=>{
  const out=run(request([['2020-01-31',10],['2020-03-02',10],['2020-03-31',10],['2020-04-30',10],['2020-05-01',10]],{}, {startDate:'2020-01-31'}));
  assert.equal(out.replay.contributions,4); assert.equal(out.replay.principal,400); near(out.replay.endValue,400);
});
test('terminal observation is valuation only and initial purchase remains separate',()=>{
  const out=run(request([['2020-01-01',10],['2020-01-02',10],['2020-01-03',10]],{frequency:'daily',initial:50}));
  assert.equal(out.replay.contributions,2); assert.equal(out.replay.principal,250);
});
test('whole lots carry cash until a purchase is possible',()=>{
  const out=run(request([['2020-01-01',10],['2020-01-02',10],['2020-01-03',10],['2020-01-04',20]],{frequency:'daily',payment:15,unitMode:'whole',lotSize:2}));
  assert.equal(out.replay.principal,45); near(out.replay.cashQuote,5); near(out.replay.endValue,85);
});
test('historical FX values each purchase and ending balance on its date',()=>{
  const out=run(request([['2020-01-02',10],['2021-01-04',10]],{payment:0,initial:100,fxRate:7,fxMode:'historical',fxPoints:[['2020-01-02',7],['2021-01-04',6]]}));
  near(out.replay.endValue,600/7); assert.equal(out.replay.startFx,7); assert.equal(out.replay.endFx,6);
});
test('CPI changes real value but not nominal value',()=>{
  const out=run(request([['2020-01-01',10],['2021-01-01',10]],{initial:110,payment:0,inflationMode:'historical',cpiPoints:[['2020-01-01',100],['2021-01-01',110]]}));
  near(out.replay.endValue,110); near(out.replay.realEndValue,100);
});
test('fees are counterfactual, do not lower historical account value',()=>{
  const points=[['2020-01-01',10],['2021-01-01',12]];
  const zero=run(request(points,{initial:100,payment:0,feeRate:0}));
  const fee=run(request(points,{initial:100,payment:0,feeRate:1}));
  near(zero.replay.endValue,fee.replay.endValue); assert.ok(fee.replay.feeDrag>0);
  const unknown=run(request(points,{feeRate:null})); assert.equal(unknown.replay.feeDrag,null); assert.equal(unknown.replay.feeRateKnown,false);
});
test('short history retains factual metrics and no annualization',()=>{
  const out=run(request([['2020-01-01',10],['2020-01-02',9]]));
  assert.equal(out.metrics.cagr,null); near(out.metrics.maxDrawdown,-10); assert.equal(out.rolling,null); assert.ok(out.warnings.includes('REQUESTED_WINDOW_SHORTENED_TO_AVAILABLE_HISTORY'));
});
test('single observation returns initial value and zero installments',()=>{
  const out=run(request([['2020-01-01',10]],{initial:100}));
  near(out.replay.endValue,100); assert.equal(out.replay.contributions,0); assert.equal(out.metrics.cagr,null);
});
test('recovered and unresolved drawdowns remain distinct',()=>{
  const points=[['2020-01-01',100],['2020-01-02',80],['2020-01-03',100]];
  const recovered=run(request(points)).metrics; assert.equal(recovered.recovered,true); assert.equal(recovered.recoveryDays,1); assert.equal(recovered.peakToRecoveryDays,2);
  const pending=run(request(points.slice(0,2))).metrics; assert.equal(pending.recovered,false); assert.equal(pending.recoveryDate,null);
});
test('indices accept statistics only and reject DCA',()=>{
  const req=request([['2020-01-01',10],['2020-01-02',9]],{}, {instrumentKind:'index'});
  assert.equal(engine.analyze(req).ok,false); delete req.options;
  const out=run(req); assert.equal(out.mode,'index-context'); assert.equal(out.replay,null);
  assert.equal(engine.analyze({...req,mode:'replay'}).ok,false);
});
test('rolling ranks whole observed paths and lower median',()=>{
  const out=run(request(syntheticPoints(),{}, {requestedYears:1,mode:'rolling'}));
  assert.ok(out.rolling.samples>20); assert.ok(out.rolling.worst.multiple<=out.rolling.median.multiple); assert.ok(out.rolling.median.multiple<=out.rolling.best.multiple);
});
test('start after history is rejected; provenance is preserved',()=>{
  const req=request([['2020-01-01',10]],{}, {startDate:'2021-01-01'}); assert.equal(engine.analyze(req).ok,false);
  delete req.startDate; req.history.sourceUrl='https://example.com/source'; assert.equal(run(req).source.sourceUrl,req.history.sourceUrl);
});

test('comparison excludes the first observation after common end',()=>{
  const first=request([['2020-01-01',10],['2020-01-03',12],['2020-01-05',15]]);
  const second=request([['2020-01-02',20],['2020-01-04',21]]);
  const out=engine.compare({first,second}); assert.equal(out.ok,true,JSON.stringify(out));
  assert.equal(out.commonStart,'2020-01-02');assert.equal(out.commonEnd,'2020-01-04');
  assert.equal(out.first.replay.end,'2020-01-03');assert.equal(out.second.replay.end,'2020-01-04');
});
